services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.2:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  kafdrop:
    image: obsidiandynamics/kafdrop:4.0.2
    container_name: kafdrop
    restart: always
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
    depends_on:
      - kafka
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: myprassword
      POSTGRES_DB: cs366
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com # Email สำหรับล็อกอิน PGAdmin
      PGADMIN_DEFAULT_PASSWORD: admin # รหัสผ่านสำหรับล็อกอิน PGAdmin
    ports:
      - "4500:80" # Mapping port 80 ของ PGAdmin ไปยัง host
    depends_on:
      - postgres

  order-service:
    image: openjdk:21
    container_name: order
    restart: always
    working_dir: /app
    volumes:
      - ./Microservice-Artifact:/app
    ports:
      - "8080:8080"
    command: ["java", "-jar", "/app/order-service.jar"]
    depends_on:
      - kafka
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cs366
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: myprassword
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  payment-service:
    image: openjdk:21
    container_name: payment
    restart: always
    working_dir: /app
    volumes:
      - ./Microservice-Artifact:/app
    ports:
      - "8081:8080"
    command: ["java", "-jar", "/app/payment-service.jar"]
    depends_on:
      - kafka
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cs366
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: myprassword
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  rider-service:
    image: openjdk:21
    container_name: rider
    restart: always
    working_dir: /app
    volumes:
      - ./Microservice-Artifact:/app
    ports:
      - "8082:8080"
    command: ["java", "-jar", "/app/rider-service.jar"]
    depends_on:
      - kafka
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cs366
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: myprassword
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  restaurant-service:
    image: openjdk:21
    container_name: restaurant
    restart: always
    working_dir: /app
    volumes:
      - ./Microservice-Artifact:/app
    ports:
      - "8083:8080"
    command: ["java", "-jar", "/app/restaurant-service.jar"]
    depends_on:
      - kafka
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cs366
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: myprassword
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  notification-service:
    image: openjdk:21
    container_name: notification
    restart: always
    working_dir: /app
    volumes:
      - ./Microservice-Artifact:/app
    ports:
      - "8084:8080"
    command: ["java", "-jar", "/app/notification-service.jar"]
    depends_on:
      - kafka
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cs366
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: myprassword
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
